#%RAML 1.0
title: Q2C-WORK-ORDER
baseUri: localhost:8081/api/
description: This API

/health-check:
  /salesforce:
    displayName: Health_Check
    description: Call to Return Health Of Salesforce Connections
    get:
      responses:
        200:
          body:
            application/json:
              example: {"Status": "OK"}
        400:
        500:
          body:
            application/json:
              example: {"Status": "FAILURE"}
  /aria:
    displayName: Health_Check
    description: Call to Return Health Of Aria Connections
    get:
      responses:
        200:
          body:
            application/json:
              example: {"Status": "OK"}
        400:
        500:
          body:
            application/json:
              example: {"Status": "FAILURE"}
  /oracle:
    displayName: Health_Check
    description: Call to Return Health Of Oracle Connections
    get:
      responses:
        200:
          body:
            application/json:
              example: {"Status": "OK"}
        400:
        500:
          body:
            application/json:
              example: {"Status": "FAILURE"}
  /dso:
    displayName: Health_Check
    description: Call to Return Health Of DSO Connections
    get:
      responses:
        200:
          body:
            application/json:
              example: {"Status": "OK"}
        400:
        500:
          body:
            application/json:
              example: {"Status": "FAILURE"}